addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.xerial.sbt"  % "sbt-sonatype"          % "3.9.7")
addSbtPlugin("com.jsuereth"    % "sbt-pgp"               % "2.1.1")
addSbtPlugin("com.geirsson"    % "sbt-ci-release"        % "1.5.5")
addSbtPlugin("org.scalameta"   % "sbt-scalafmt"          % "2.4.0")
