addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.xerial.sbt"  % "sbt-sonatype"          % "3.9.7")
addSbtPlugin("com.jsuereth"    % "sbt-pgp"               % "2.1.1")
addSbtPlugin("com.geirsson"    % "sbt-ci-release"        % "1.5.7")
addSbtPlugin("org.scalameta"   % "sbt-scalafmt"          % "2.4.2")
addSbtPlugin("ch.epfl.scala"   % "sbt-scalafix"          % "0.9.27")
addSbtPlugin("com.47deg"       % "sbt-microsites"        % "1.3.4")
addSbtPlugin("com.eed3si9n"    % "sbt-assembly"          % "0.15.0")
